import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,Brain,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {LENSES,lensParts,lensesFor,roleIn,type Lens} from './psychology';
import {DEFAULT_VISIBLE,REGIONS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type RegionId,type View} from './anatomy';
const CORTEX:RegionId[]=['frontal','parietal','temporal','occipital'],DEEP:RegionId[]=['limbic','basal-ganglia','diencephalon','brainstem','white-matter','ventricles'];
const sameSet=(a:string[],b:string[])=>a.length===b.length&&b.every(x=>a.includes(x));
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|'lenses'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch('/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(REGIONS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeRegions=REGIONS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=REGIONS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['brain','hippocampus','amygdala','thalamus','hypothalamus','insula','cerebellum','corpus callosum','left prefrontal cortex'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const chooseLens=(l:Lens)=>{if(!atlas)return;const hits=lensParts(l,atlas.parts);setChosen({id:`lens:${l.id}`,name:l.name,elements:hits.map(h=>h.part.id)});setState(s=>({...s,selected:hits.map(h=>h.part.id),isolate:true,explode:0,rotate:false}));setDetails(true);setPanel(null);};
 const lens=chosen?.id.startsWith('lens:')?LENSES.find(l=>`lens:${l.id}`===chosen.id):undefined,roles=useMemo(()=>lens?[]:lensesFor(selectedParts),[lens,state.selected,atlas]);
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:RegionId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search'|'lenses')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> NEUROSCIENCE × PSYCHOLOGY</div><h1>Brain &amp; Psychology Atlas</h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'123'} modeled structures <span>·</span> BodyParts3D</div></header>
  <nav className="top-actions" aria-label="Explorer panels"><Button variant="ghost" className={panel==='lenses'?'active':''} onClick={()=>openPanel('lenses')} aria-label="Psychology lenses"><Brain size={18}/><span>Psychology lenses</span></Button><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Search structures"><Search size={18}/><span>Find a structure</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="About this atlas" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Brain regions">
   <div className="panel-heading"><span>Regions</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Close regions"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeRegions.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeRegions.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeRegions.map(x=>x.id)}))}>All</Button><Button variant="ghost" aria-pressed={sameSet(state.visible,CORTEX)} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:CORTEX}))}>Cortex</Button><Button variant="ghost" aria-pressed={sameSet(state.visible,DEEP)} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:DEEP}))}>Deep</Button></div>
   <div className="system-list">{activeRegions.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Show only ${s.name}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Show ${s.name}`} /></div>)}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} structures visible</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Hide all</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Find a structure"><div className="panel-heading"><span>Find a structure</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Amygdala, insula, thalamus…" aria-label="Search named brain structures" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>No structures match your search.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'mesh':'meshes'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':'Start with a region, or search every named structure.'}</p></section>}
  {panel==='lenses'&&<section className="search-panel lens-panel glass" aria-label="Psychology lenses"><div className="panel-heading"><span>Psychology lenses</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close lenses"><X size={18}/></Button></div><p className="search-note">Pick a question. The atlas highlights the structures involved and shows the evidence behind it, with its limits.</p><div className="lens-list">{LENSES.map(l=><Button variant="ghost" key={l.id} className="lens-item" onClick={()=>chooseLens(l)}><span className="lens-name">{l.name}</span><span className="lens-question">{l.question}</span></Button>)}</div></section>}
  <nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${v} view`} aria-label={`${v} view`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate brain'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name??'SELECTED STRUCTURE'):state.explode>.95?'ANATOMICAL INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':'ADULT MALE REFERENCE BRAIN'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Open brain regions"><Layers3 size={20}/><span>Regions</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Separate structures</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Assembled</span><span>Every piece</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Assemble and reset"><RotateCcw size={18}/><span>Reset</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Drag to pan':'Drag to orbit'} <b>·</b> Pinch to zoom <b>·</b> Tap to inspect</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Source & credits <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Preparing the brain</strong><span>{progress}% · Loading {atlas?.parts.length.toLocaleString()??'123'} structures</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''} ${lens?'is-lens':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:lens?'#8052ff':system?.color}}/><div className="eyebrow">{lens?'PSYCHOLOGY LENS':system?.name??'BRAIN'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?.name}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}>
   {lens&&<p className="lens-question">{lens.question}</p>}
   <SheetDescription className="structure-description">{lens?lens.summary:chosen&&selected?explanation(chosen.name,selected.system):''}</SheetDescription>
   {!lens&&chosen&&!EXPLANATIONS[chosen.name.toLowerCase().replace(/^(left|right) /,'')]&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">Region overview · structure identified from source anatomy</span>}
   {!lens&&roles.length>0&&<div className="psych-block"><h3>Psychological roles</h3>{roles.map(({lens:l,role})=><div className="psych-role" key={l.id}><Button variant="ghost" className="psych-link" onClick={()=>chooseLens(l)}>{l.name}<ChevronRight size={13}/></Button><p>{role}</p></div>)}<p className="psych-note">Roles describe what research associates with a structure, not what it does alone. Open a lens to see the evidence and its limits.</p></div>}
   <div className="structure-meta"><span>{lens?'Lens':'Atlas reference'}<strong>{lens?`${LENSES.findIndex(l=>l.id===lens.id)+1} of ${LENSES.length}`:chosen?.id}</strong></span><span>{lens?'Structures lit':'Selected meshes'}<strong>{state.selected.length.toLocaleString()}</strong></span></div>
   {lens&&<div className="psych-block"><h3>How each structure contributes</h3>{selectedParts.map(p=><div className="psych-role" key={p.id}><Button variant="ghost" className="psych-link" onClick={()=>choosePart(p.id)}>{p.name}<ChevronRight size={13}/></Button><p>{roleIn(lens,p.name)}</p></div>)}</div>}
   {lens&&<div className="psych-block"><h3>Evidence</h3>{lens.evidence.map(e=><div className="psych-evidence" key={e.source}><p>{e.finding}</p><span><b>{e.kind}</b> · {e.source}</span></div>)}</div>}
   {lens&&<div className="psych-block"><h3>Clinical and applied relevance</h3>{lens.conditions.map(c=><div className="psych-role" key={c.name}><strong>{c.name}</strong><p>{c.note}</p></div>)}</div>}
   {lens&&<div className="psych-block"><h3>Not in this model</h3><p className="psych-plain">{lens.notModeled}</p></div>}
   {lens&&<div className="psych-block psych-caution"><h3>Read with care</h3><p className="psych-plain">{lens.caution}</p></div>}
   {!lens&&selectedParts.length>1&&<div className="member-list"><h3>Included structures</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>And {selectedParts.length-50} more modeled meshes.</p>}</div>}
   <a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">View anatomical source <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Show surrounding brain':lens?'Isolate these structures':'Isolate structure'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>Clear selection</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">SOURCE & SCOPE</div><SheetTitle className="structure-title">A brain, in context.</SheetTitle><SheetDescription>Explore the adult male reference brain from BodyParts3D through ten questions psychologists ask.</SheetDescription><div className="about-copy"><p><strong>Anatomy · BodyParts3D</strong><br/>{atlas?atlas.parts.length:123} individual meshes drawn from an adult male reference anatomy: cortex, limbic system, basal ganglia, thalamus and hypothalamus, brainstem, cerebellum, white-matter tracts, ventricles and a glass skull.</p><p><strong>Psychology · lenses</strong><br/>Each lens links a psychological question to the structures research associates with it, with landmark studies, clinical relevance, what this model leaves out, and why the claim should be read with care. Content is a teaching summary authored for this atlas and should be checked against primary sources before being cited.</p><p>This is a single male reference, not a population. Mesh boundaries follow anatomical convention and do not match functional parcellations, so a gyrus is only an approximation of a functional area. Findings about brain regions describe group-level associations, not diagnoses or individual traits. This is an educational reference, not a clinical tool.</p><h3>Source</h3><p>BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">Dataset license <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">Original geometry & metadata <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">Read the source publication <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
